//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM_WEB_APP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrollment
    {
        public int ID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> TraineeID { get; set; }

        [Range(0, 10)]
        public Nullable<int> Grade { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
